#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'sidekiq/api'

Sidekiq::Queue.all.each do |q|
  # compatible with custom log-based metrics of Librato
  # https://devcenter.heroku.com/articles/librato#custom-log-based-metrics
  puts "measure#sidekiq.#{q.name}.count=#{q.size}"
  puts "measure#sidekiq.#{q.name}.latency=#{q.latency}"
end
