#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'sidekiq/api'

TYPE = ARGV[0]

queues = Sidekiq::Queue.all
stats = Sidekiq::Stats.new

exit 0 if queues.empty?

# e.g. sample#sidekiq.default.size=0 sample#sidekiq.mailer.size=0
puts queues.map {|q| "#{TYPE}#sidekiq.#{q.name}.size=#{q.size}" }.join(' ')

# e.g. sample#sidekiq.default.latency=0 sample#sidekiq.mailer.latency=0
puts queues.map {|q| "#{TYPE}#sidekiq.#{q.name}.latency=#{q.latency}" }.join(' ')

# e.g. sample#sidekiq.all.size=0
puts "#{TYPE}#sidekiq.all.size=#{stats.enqueued}"
