#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'sidekiq/api'

queues = Sidekiq::Queue.all

# e.g. sample#sidekiq.default.size=0 sample#sidekiq.mailer.size=0
puts queues.map {|q| "sample#sidekiq.#{q.name}.size=#{q.size}" }.join(' ')

# e.g. sample#sidekiq.default.latency=0 sample#sidekiq.mailer.latency=0
puts queues.map {|q| "sample#sidekiq.#{q.name}.latency=#{q.latency}" }.join(' ')
